export const APP_ROUTES = {
  root: () => "/",
  solutions: () => "/solutions",
  features: () => "/features",
  pricing: () => "/pricing",
  about: () => "/about",
  contact: () => "/contact",
  resources: () => "/resources",
  blog: () => "/blog",
  bookDemo: () => "/book-demo",
  privacy: () => "/privacy",
  terms: () => "/terms",
  app: () => "https://enterprise.storeatark.com/sign-up",
  gopher: () => "https://gopher.storeatark.com",
};
