import { IntervalEnum } from "@/types";

export const PRICING_PLANS = {
  monthly: [
    {
      id: "68966d88e582ae9aa7a5bf4b",
      name: "Trial Plan",
      description: "A free trial plan with limited access to core features.",
      planType: "TRIAL",
      price: 0,
      summary: [
        "Free for 14 days",
        "Access to basic modules",
        "Limited number of outlets and centres",
        "Includes Supplier Management",
      ],
      code: "TRIAL-14DAYS",
      currency: "NGN",
      interval: "MONTHLY",
      isActive: false,
      features: [
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Supplier Management",
          description: "Manage your suppliers effectively",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Retail Outlet",
          description: "Manage retail outlets",
          limitType: "NUMERIC",
          limit: 1,
        },
      ],
    },
    {
      id: "686fc9318f07e6552d51ea42",
      name: "Basic",
      description: "Basic features and perfect for startups",
      planType: "BASIC",
      price: 15000,
      summary: [
        "Core inventory & dashboard functionality for up to 2 users",
        "CSV import/export limited to inventory only",
        "Enables management of one fulfillment centre and one outlet only",
        "Customizable roles",
      ],
      code: "PLN_lklb7w8s36krhxt",
      currency: "NGN",
      interval: "MONTHLY",
      isActive: false,
      features: [
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 2",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export support for inventory module only",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9338f07e6552d51ea4e",
      name: "Basic Plus",
      description: "Advanced features for small teams",
      planType: "BASIC",
      price: 30000,
      summary: [
        "Everything in Basic",
        "Up to 5 users",
        "Audit logs",
        "Activity tracking",
        "Basic CSV export across modules - inventory, fulfilment centre, and purchase order modules",
        "Enables management of one fulfillment centre and two outlets only",
        "Bulk CSV import/export",
      ],
      code: "PLN_ri4bz0fj66ir5e7",
      currency: "NGN",
      interval: "MONTHLY",
      isActive: false,
      features: [
        {
          name: "Users",
          description: "Limit: 5",
          limitType: "NUMERIC",
          limit: 5,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, and link bills to POs",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9358f07e6552d51ea63",
      name: "Standard",
      description: "Advanced features for growing businesses",
      planType: "STANDARD",
      price: 65000,
      summary: [
        "Everything in Basic +",
        "Up to 10 users",
        "Enables management of one fulfillment centre and multiple outlets",
        "Basic CSV export across modules - inventory, fulfilment centre, purchase order and purchase request modules",
        "Full management of procurement flows (requests, POs, bills, suppliers)",
        "Scheduled weekly reports",
      ],
      code: "PLN_1t39ifzmmqt0zag",
      currency: "NGN",
      interval: "MONTHLY",
      isActive: false,
      features: [
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 10",
          limitType: "NUMERIC",
          limit: 10,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled reports and insights",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9378f07e6552d51ea78",
      name: "Premium",
      description: "Full feature access for enterprises",
      planType: "PREMIUM",
      price: 120000,
      summary: [
        "All Standard features",
        "Up to 15 users",
        "Full CSV import/export across all modules - Bills, Purchase Requests, Purchase Orders & Suppliers",
        "Enables management of unlimited fulfillment centres and outlets",
        "Unlimited custom reports",
        "Dedicated customer support rep",
        "Partial bill tracking (split payments on bills)",
        "API Integration",
      ],
      code: "PLN_inexiqzhchb82cs",
      currency: "NGN",
      interval: "MONTHLY",
      isActive: false,
      features: [
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 15",
          limitType: "NUMERIC",
          limit: 15,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export across all modules",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled and custom reports",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "API Integration",
          description: "Enable API sync with external tools like QuickBooks",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Dedicated Customer Support",
          description: "Access to a dedicated customer support representative",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
  ],
  semester: [
    {
      id: "686fc9328f07e6552d51ea46",
      name: "Basic",
      description: "Basic features and perfect for startups",
      planType: "BASIC",
      price: 13500,
      summary: [
        "Core inventory & dashboard functionality for up to 2 users",
        "CSV import/export limited to inventory only",
        "Enables management of one fulfillment centre and one outlet only",
        "Customizable roles",
      ],
      code: "PLN_gpml50bv4hfcovn",
      currency: "NGN",
      interval: "SEMESTER",
      isActive: false,
      features: [
        {
          name: "Users",
          description: "Limit: 2",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export support for inventory module only",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9348f07e6552d51ea55",
      name: "Basic Plus",
      description: "Advanced features for small teams",
      planType: "BASIC",
      price: 27000,
      summary: [
        "Everything in Basic",
        "Up to 5 users",
        "Audit logs",
        "Activity tracking",
        "Basic CSV export across modules - inventory, fulfilment centre, and purchase order modules",
        "Enables management of one fulfillment centre and two outlets only",
        "Bulk CSV import/export",
      ],
      code: "PLN_h3g9hcjupttchlb",
      currency: "NGN",
      interval: "SEMESTER",
      isActive: false,
      features: [
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 5",
          limitType: "NUMERIC",
          limit: 5,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, and link bills to POs",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9368f07e6552d51ea6a",
      name: "Standard",
      description: "Advanced features for growing businesses",
      planType: "STANDARD",
      price: 58500,
      summary: [
        "Everything in Basic +",
        "Up to 10 users",
        "Enables management of one fulfillment centre and multiple outlets",
        "Basic CSV export across modules - inventory, fulfilment centre, purchase order and purchase request modules",
        "Full management of procurement flows (requests, POs, bills, suppliers)",
        "Scheduled weekly reports",
      ],
      code: "PLN_p2r12pn2cs1hcre",
      currency: "NGN",
      interval: "SEMESTER",
      isActive: false,
      features: [
        {
          name: "Users",
          description: "Limit: 10",
          limitType: "NUMERIC",
          limit: 10,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled reports and insights",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9388f07e6552d51ea81",
      name: "Premium",
      description: "Full feature access for enterprises",
      planType: "PREMIUM",
      price: 108000,
      summary: [
        "All Standard features",
        "Up to 15 users",
        "Full CSV import/export across all modules - Bills, Purchase Requests, Purchase Orders & Suppliers",
        "Enables management of unlimited fulfillment centres and outlets",
        "Unlimited custom reports",
        "Dedicated customer support rep",
        "Partial bill tracking (split payments on bills)",
        "API Integration",
      ],
      code: "PLN_yx5y9jz3dl45xuj",
      currency: "NGN",
      interval: "SEMESTER",
      isActive: false,
      features: [
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 15",
          limitType: "NUMERIC",
          limit: 15,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export across all modules",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled and custom reports",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "API Integration",
          description: "Enable API sync with external tools like QuickBooks",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Dedicated Customer Support",
          description: "Access to a dedicated customer support representative",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
  ],
  annually: [
    {
      id: "686fc9338f07e6552d51ea4a",
      name: "Basic",
      description: "Basic features and perfect for startups",
      planType: "BASIC",
      price: 12750,
      summary: [
        "Core inventory & dashboard functionality for up to 2 users",
        "CSV import/export limited to inventory only",
        "Enables management of one fulfillment centre and one outlet only",
        "Customizable roles",
      ],
      code: "PLN_5rp0qniat3ruby7",
      currency: "NGN",
      interval: "ANNUALLY",
      isActive: false,
      features: [
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 2",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export support for inventory module only",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9358f07e6552d51ea5c",
      name: "Basic Plus",
      description: "Advanced features for small teams",
      planType: "BASIC",
      price: 25500,
      summary: [
        "Everything in Basic",
        "Up to 5 users",
        "Audit logs",
        "Activity tracking",
        "Basic CSV export across modules - inventory, fulfilment centre, and purchase order modules",
        "Enables management of one fulfillment centre and two outlets only",
        "Bulk CSV import/export",
      ],
      code: "PLN_e33k0hbrzyq59hu",
      currency: "NGN",
      interval: "ANNUALLY",
      isActive: false,
      features: [
        {
          name: "Users",
          description: "Limit: 5",
          limitType: "NUMERIC",
          limit: 5,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed",
          limitType: "NUMERIC",
          limit: 2,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, and link bills to POs",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9378f07e6552d51ea71",
      name: "Standard",
      description: "Advanced features for growing businesses",
      planType: "STANDARD",
      price: 55250,
      summary: [
        "Everything in Basic +",
        "Up to 10 users",
        "Enables management of one fulfillment centre and multiple outlets",
        "Basic CSV export across modules - inventory, fulfilment centre, purchase order and purchase request modules",
        "Full management of procurement flows (requests, POs, bills, suppliers)",
        "Scheduled weekly reports",
      ],
      code: "PLN_94at0v1rpet455y",
      currency: "NGN",
      interval: "ANNUALLY",
      isActive: false,
      features: [
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Users",
          description: "Limit: 10",
          limitType: "NUMERIC",
          limit: 10,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export for inventory module",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed",
          limitType: "NUMERIC",
          limit: 1,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled reports and insights",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
    {
      id: "686fc9398f07e6552d51ea8a",
      name: "Premium",
      description: "Full feature access for enterprises",
      planType: "PREMIUM",
      price: 102000,
      summary: [
        "All Standard features",
        "Up to 15 users",
        "Full CSV import/export across all modules - Bills, Purchase Requests, Purchase Orders & Suppliers",
        "Enables management of unlimited fulfillment centres and outlets",
        "Unlimited custom reports",
        "Dedicated customer support rep",
        "Partial bill tracking (split payments on bills)",
        "API Integration",
      ],
      code: "PLN_upkd45mygtz5nhh",
      currency: "NGN",
      interval: "ANNUALLY",
      isActive: false,
      features: [
        {
          name: "Users",
          description: "Limit: 15",
          limitType: "NUMERIC",
          limit: 15,
        },
        {
          name: "Audit logs",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Activity tracking",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "CSV/Excel uploads/downloads",
          description: "Included",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Custom Roles",
          description: "Support for custom role and permission management",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Inventory Import/Export",
          description: "CSV import/export across all modules",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Fulfillment Centre",
          description: "Number of fulfillment centres allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Retail Outlet",
          description: "Number of retail outlets allowed (unlimited)",
          limitType: "NUMERIC",
          limit: 999999999,
        },
        {
          name: "Supplier Management",
          description: "Create, update, and delete suppliers",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Purchase Request & Order Management",
          description: "Manage purchase requests & orders",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Bill Management",
          description: "Create, track, link, and partially pay bills",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Alert Center",
          description: "View alerts and apply filters for events and actions",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Reports & Insights",
          description: "Access to scheduled and custom reports",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Email Support",
          description: "Access to email-based customer support",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "API Integration",
          description: "Enable API sync with external tools like QuickBooks",
          limitType: "BOOLEAN",
          limit: null,
        },
        {
          name: "Dedicated Customer Support",
          description: "Access to a dedicated customer support representative",
          limitType: "BOOLEAN",
          limit: null,
        },
      ],
    },
  ],
};

export const PRICING_PERIODS = [
  { value: IntervalEnum.MONTHLY, label: "Monthly" },
  { value: IntervalEnum.SEMESTER, label: "6 months" },
  { value: IntervalEnum.ANNUAL, label: "Annual" },
] as const;
